'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const SIZES = [['A5',349],['A4',449],['A3',549],['A2',749],['A1',1099],['A0',1799]] as const

export default function AdminPage(){
 const supabase=useMemo(()=>createClient(),[])
 const [user,setUser]=useState<any>(null),[isAdmin,setIsAdmin]=useState(false),[checking,setChecking]=useState(true),[products,setProducts]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();setUser(data.user);if(data.user){const {data:admin}=await supabase.rpc('is_admin');setIsAdmin(!!admin);if(admin)await loadProducts()}setChecking(false)})()},[])
 async function loadProducts(){const {data,error}=await supabase.from('products').select('id,name,slug,description,short_description,price,compare_at_price,stock,is_active,is_featured').order('created_at',{ascending:false});if(error)setMessage(error.message);else setProducts(data||[])}
 async function save(){if(!selected||!isAdmin)return;setBusy(true);setMessage('');const {error}=await supabase.from('products').update({name:selected.name,slug:selected.slug,description:selected.description,short_description:selected.short_description,price:Number(selected.price)||0,compare_at_price:selected.compare_at_price?Number(selected.compare_at_price):null,stock:Number(selected.stock)||0,is_active:!!selected.is_active,is_featured:!!selected.is_featured,updated_at:new Date().toISOString()}).eq('id',selected.id);setMessage(error?error.message:'Artwork saved successfully.');if(!error)await loadProducts();setBusy(false)}
 if(checking)return <main className="admin-shell"><div className="admin-card"><span className="eyebrow">SkyShotConner</span><h1>Checking access…</h1></div></main>
 if(!user)return <main className="admin-shell"><div className="admin-card"><span className="eyebrow">SkyShotConner</span><h1>Admin dashboard</h1><p>Sign in to your SkyShotConner account first.</p><a className="admin-button" href="/login">Sign in</a></div></main>
 if(!isAdmin)return <main className="admin-shell"><div className="admin-card"><span className="eyebrow">SkyShotConner / Control</span><h1>Access denied.</h1><p>Your account is signed in, but it is not registered as an administrator. The store database will also reject product edits unless the Supabase admin policy allows your account.</p><a className="admin-button" href="/">Return to store</a></div></main>
 return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">SkyShotConner / Control</span><h1>Admin dashboard</h1><p>Manage artwork details, pricing, stock and visibility.</p></div><a className="admin-link" href="/">View store ↗</a></header><section className="admin-grid"><div className="admin-card"><div className="admin-card-head"><h2>Artworks</h2><button className="admin-button secondary-admin" onClick={loadProducts}>Refresh</button></div>{products.map(p=><button key={p.id} className={'admin-product '+(selected?.id===p.id?'selected':'')} onClick={()=>setSelected({...p})}><span>{p.name}</span><small>{p.is_active?'Published':'Hidden'} · {p.stock??0} stock</small></button>)}</div><div className="admin-card editor-card">{selected?<><div className="admin-card-head"><div><span className="eyebrow">Edit artwork</span><h2>{selected.name}</h2></div></div><div className="admin-form"><label>Name<input value={selected.name||''} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Slug<input value={selected.slug||''} onChange={e=>setSelected({...selected,slug:e.target.value})}/></label><label>Short description<textarea value={selected.short_description||''} onChange={e=>setSelected({...selected,short_description:e.target.value})}/></label><label>Description<textarea rows={6} value={selected.description||''} onChange={e=>setSelected({...selected,description:e.target.value})}/></label><div className="admin-row"><label>Base price<input type="number" value={selected.price??0} onChange={e=>setSelected({...selected,price:e.target.value})}/></label><label>Compare price<input type="number" value={selected.compare_at_price??''} onChange={e=>setSelected({...selected,compare_at_price:e.target.value})}/></label><label>Stock<input type="number" value={selected.stock??0} onChange={e=>setSelected({...selected,stock:e.target.value})}/></label></div><div className="admin-sizes"><span className="eyebrow">Canvas prices</span><div>{SIZES.map(([size,price])=><span key={size}><b>{size}</b> R{price.toLocaleString('en-ZA')}</span>)}</div></div><label className="check"><input type="checkbox" checked={!!selected.is_active} onChange={e=>setSelected({...selected,is_active:e.target.checked})}/> Published</label><label className="check"><input type="checkbox" checked={!!selected.is_featured} onChange={e=>setSelected({...selected,is_featured:e.target.checked})}/> Featured</label><button className="admin-button" disabled={busy} onClick={save}>{busy?'Saving…':'Save artwork'}</button>{message&&<p className="admin-message">{message}</p>}</div></>:<div className="admin-empty"><span className="eyebrow">Select an artwork</span><h2>Choose a product to edit.</h2><p>Changes are saved directly to your connected Supabase products table.</p></div>}</div></section></main>
}
